### ISSUE TITLE
Overlay disappear

### ISSUE THREAD

**Issue by Qoooo** [RainbowMage/OverlayPlugin#14]
Now using the newest version, when alt+tab out of the game and back in, sometimes the overlay will disappear. Previously when using the older version, I'm able to alt+tab to find the overlay and get it to appear again, now with the new version, I'm not able to. The only way is to uncheck and check on the display overlay check box.

**Comment by RainbowMage** [comment]
I have released [experimental build](https://github.com/RainbowMage/OverlayPlugin/releases/tag/0.2.5.1_expr) which contains code to fix disappear problem.
Please report if the build was fixed your problem if you can.

**Comment by Qoooo** [comment]
Tested out with version 0.2.5.1, now the overlay will reappear after alt+tab.  :)

**Comment by RainbowMage** [comment]
Thank you for testing.
Closing this issue as the problem has been resolved.
