### ISSUE TITLE
Overlay not showing up in obs

### ISSUE THREAD

**Issue by morpheus305** [RainbowMage/OverlayPlugin#15]
This use to not be a problem until the x64 upate to act and the recent updates to the overlay plugin. The overlay window use to show up as "HtmlRenderer" in windows. When you alt tabbed through your windows you would see it. Now it's not there anymore so in obs you can't window capture the overlay cause it won't show in the pull down list. Is there anyway to fix this?

**Comment by RainbowMage** [comment]
I have changed the overlay window style to hide from Alt+Tab window candidates at the commit 7909f30ca484c7b08a4172e6d5b1fe72efe7a86f.

This is by design. Please use another method to capture overlays.
