### ISSUE TITLE
Combattant not showing 

### ISSUE THREAD

**Issue by Angyo** [RainbowMage/OverlayPlugin#18]
Hi, the plugins seems to work, for example i have the timer encounter who increment itself, but i'm unable to see combattant datas, nothing.

![screenshot](https://cloud.githubusercontent.com/assets/1088341/6548500/55d05e10-c5fb-11e4-8375-f487db785016.png)

**Comment by carwin** [comment]
Same issue.

**Comment by billyvg** [comment]
This is probably due to the FFXIV ACT plugin not properly parsing.  Make sure you run ACT as admin AND allow ACT in your firewall (I had to disable my firewall completely to get it to work).

You could also "Disable Networking Parsing" but it won't be as accurate.

**Comment by RainbowMage** [comment]
I confirmed this behavior today.

ACT_FFXIV_Plugin sometimes marks allied player as "not allied player". (I don't know that's why.)

This is not an issue of OverlayPlugin.

**Comment by carwin** [comment]
Ah yep, the firewall was the issue for me. Thanks @billyvg / @RainbowMage.
