### ISSUE TITLE
レンダラー

### ISSUE THREAD

**Issue by kikyo1212** [RainbowMage/OverlayPlugin#20]
お疲れ様です。

こちらのhtmlのレンダラーは何を元に用いていらっしゃるのでしょうか？

win7x64環境で超極細ゴシック等の細いフォントを指定した際に，フォントサイズが小さい場合(12px等)ビットマップフォント(アンチエイリアスが効いていないもの)に差し替えられてしまいます。
該当htmlをchromeで読み込んだ場合は正常に指定したフォントが表示されますので，
元となっているレンダラーをご教授頂ければ調整を試みたい所存です。

宜しくお願い致します。

**Comment by RainbowMage** [comment]
Chromium Embedded Framework というライブラリのバージョン3.2171.1949を、CefGlueというラッパーライブラリを通して使用しています。

描画エンジン自体は Google Chrome と同じものですが、レンダリングの設定（ソフトウェアレンダリングかハードウェアレンダリングか、Direct Draw を使用するか否か）が異なっている可能性があります。
