### ISSUE TITLE
Click events inside of web view

### ISSUE THREAD

**Issue by billyvg** [RainbowMage/OverlayPlugin#21]
Is there a way we can get click events inside of the web view to propagate?

It would be useful to be able to click inside of the overlay to switch views (i.e. switch from DPS view to Healing view to Tanking view).  This way we can minimize clutter while still having a lot more flexibility.

**Comment by RainbowMage** [comment]
There is currently no way of getting click event because mouse related handlers is not implemented on the HTML renderer.

I'm going to implement that.

**Comment by RainbowMage** [comment]
Mouse and keyboard handling on the overlay has implemented. Please try.

**Comment by billyvg** [comment]
:thumbsup: Works, thank you!
