### ISSUE TITLE
"Plugin Initialization Failed"

### ISSUE THREAD

**Issue by Quietess** [RainbowMage/OverlayPlugin#24]
Hi, was very excited to use your plugin, but as I was enabling it in ACT, I was getting the following error:

"An attempt was made to laod an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information."

I have .NET framework 4.5.1, so I don't know what is causing this issue, and I don't know how to enable the loadFromRemoteSources switch.

**Comment by RainbowMage** [comment]
Your ACT or plugin binary has blocked by windows and/or placed on the network location. Please unblock the file and/or move binary into local location (such as C:\ drive).

**Comment by Quietess** [comment]
My ACT is already located in C:\ and is also on my firewall's exception list.

**Comment by RainbowMage** [comment]
So, your binary is blocked by windows. Please read README.md before use.

**Comment by BeelzKaiser** [comment]
hi i have the same error and i do all is write in the README.md but nothing change
