### ISSUE TITLE
Changing active encounter to selected

### ISSUE THREAD

**Issue by Mephi-Dross** [RainbowMage/OverlayPlugin#26]
Currently, the miniparse overlay will always show the active/latest active encounter. Is it possible to add a change, where you can say, click a checkbox on the MiniParseConfigPanel where it'll change from active encounter to the one you have selected on the ACT main window?

It would be a nice to have feature for viewing encounter reports without having to go through ACT everytime.

**Comment by RainbowMage** [comment]
You mean you want to compare active encounter with selected encounter at the "Main" tab using two miniparse overlays?

If so, I can't implement that easily due to ACT doesn't implements and exports property like "SelectedEncounter".

**Comment by Mephi-Dross** [comment]
No, I mean to have one overlay active and depending on what I have selected in the main window, the data on the overlay changes.

**Comment by RainbowMage** [comment]
ACT doesn't implements and exports function to get currently selected encounter on the main window.

I have to read an internal code of the ACT using the decompiler to do that and would be a painful work.

**Comment by Mephi-Dross** [comment]
I see. Seems kinda weird that there's no way to do that, as it seems useful to have. Thanks for the answer though.
