### ISSUE TITLE
Hide/Show Overlay with Shortkey CTRL+M / S

### ISSUE THREAD

**Issue by Jyntax** [RainbowMage/OverlayPlugin#3]
Hello there,

as far as I can tell CTRL+m and CTRL+S should Hide/Show the Miniparse or Spelltimer Overlay but it isn't working. Can you help me with that maybe? o:

Best regards,
Jyntax

EDIT: K it works but just if I have ACT as the activ window. Is there a workaround for that? Since I want to be able to hide the Spelltimer if I'm not fighting and tabbing out and in is kinda... Not that usefull if there is a shortcut for it. xD

**Comment by elena-v2** [comment]
What I think would be better is how **GB19xx/ACT.TPMonitor** handles it, in particular it has an option to hide the overlay when FFXIV is not the active window.

When I get some free time, I can try to implement this (automatically hiding the overlay) and submit a pull request if nobody else has done so.

**Comment by RainbowMage** [comment]
Closed by the global hotkey was implemented.
