### ISSUE TITLE
FullScreen Dx11 miniparser not displayed.

### ISSUE THREAD

**Issue by DarkBraska** [RainbowMage/OverlayPlugin#31]
Hello and thank you for your work, miniparser not displayed in fullscreen mode , in borderless windowed mode works well .

In Dx9 if the miniparser shown in full screen

It will be possible in the future the work miniparser DX11 fullscreen mode ?

**Comment by ezsoftware** [comment]
OverlayPlugin does not support true full screen in any version of Direct X, so you must be mis-remembering the DX9 or you're running DX9 in Borderless Windowed.

Also, its unlikely to come any time soon due to the development requirements that full screen overlay injection requires.
