### ISSUE TITLE
New jobs icons are missing

### ISSUE THREAD

**Issue by TriDni** [RainbowMage/OverlayPlugin#32]
The MCH, DRK and AST icons are missing from the last package.

Can you add this to the next release ?

**Comment by ezsoftware** [comment]
RainbowMage does not include job icons in his repository due to it violating SE's ToS as 3rd party applications aren't authorized for use of the official icons and such.  Other people include them, if you want to find an update that includes them, look on reddit.

**Comment by TriDni** [comment]
Ok I didn't know that :S I'll check on Reddit Thanks !
