### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by insperace** [RainbowMage/OverlayPlugin#36]
Build FAILED.

"C:\Users\inspe_000\Downloads\OverlayPlugin-master\OverlayPlugin-master\OverlayPlugin.sln" (Rebuild target) (1) ->
"C:\Users\inspe_000\Downloads\OverlayPlugin-master\OverlayPlugin-master\OverlayPlugin.Core\OverlayPlugin.Core.csproj" (Rebuild target) (2) ->
(GenerateSatelliteAssemblies target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(2863,5): error MSB3086: Task could not find "AL.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\
Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Mic
rosoft Windows SDK is installed [C:\Users\inspe_000\Downloads\OverlayPlugin-master\OverlayPlugin-master\OverlayPlugin.Core\OverlayPlugin.Core.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.16

**Comment by ezsoftware** [comment]
compiles fine for me under windows 10, from rainbowmage's build.bat, my custom build file, and from visual studio 2015 community edition.  I would suggest using one of the pre-compiled binary releases.

**Comment by pkminer30** [comment]
I am running windows 10 pro - 64 Bit. I have tried playing in dx 9 and dx 11. I have .net framework 4.5.1 installed. I am unable to use the overlay parse and for some reason the mini parser doesn't give any results either. Any idea how i can get this parser working for ffxiv?

**Comment by RainbowMage** [comment]
Cleaning up old issues.

Please repost if you have not resolve the issues yet.
