### ISSUE TITLE
object reference not set to an instance of an object spam

### ISSUE THREAD

**Issue by Lockaroonie** [RainbowMage/OverlayPlugin#37]
Whenever i try to activate the overlayplugin.dll, I get spammed by a window with that message popping up over and over and over again. The plugin has been working fine for months and only suddenly has it stopped working.
Here's a log of what happens.
Application-Start 2015-08-24T16:34:35 (v3.2.0     Release: 250 | CLR v4.0.30319.34014 | OS Microsoft Windows NT 6.2.9200.0)
***** 2015-08-24T16:34:36 - Entering InitACT
***** 2015-08-24T16:34:37 - Entering LoadNewSettings
***** 2015-08-24T16:34:37 - Config loading plugin from: C:\Users\Cesar\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
***** 2015-08-24T16:34:37 - Enabling plugin: C:\Users\XXX\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
***** 2015-08-24T16:34:37 - LogFileChanged: C:\Users\XXX\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20150824.log - 2015-08-24T15:39:39 - 2015-08-24T16:34:30 - 1624823
***** 2015-08-24T16:34:37 - Exiting LoadNewSettings
***** 2015-08-24T16:34:38 - LogFileChanged: C:\Users\XXX\AppData\Roaming\Advanced Combat Tracker\FFXIVLogs\Network_20150824.log - 2015-08-24T15:39:39 - 2015-08-24T16:34:30 - 1625547
***** 2015-08-24T16:34:38 - Checking for program updates
***** 2015-08-24T16:34:38 - Exiting InitACT: 1218.87
***** 2015-08-24T16:35:43 - Enabling plugin: C:\Program Files (x86)\Advanced Combat Tracker\Build\OverlayPlugin.dll
*****
2015-08-24T16:35:44
Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.ThreadPoolWorkQueue.Dequeue(ThreadPoolWorkQueueThreadLocals tl, IThreadPoolWorkItem& callback, Boolean& missedSteal)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
*****
*****
2015-08-24T16:35:44
Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.ThreadPoolWorkQueue.Dequeue(ThreadPoolWorkQueueThreadLocals tl, IThreadPoolWorkItem& callback, Boolean& missedSteal)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
*****
*****
2015-08-24T16:35:44
Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.ThreadPoolWorkQueue.Dequeue(ThreadPoolWorkQueueThreadLocals tl, IThreadPoolWorkItem& callback, Boolean& missedSteal)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
*****
8/24/2015 4:51:41 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Build
8/24/2015 4:51:41 PM: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
File name: 'C:\Users\XXX\AppData\Roaming\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   at RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String pluginDirectory, String path)
   at RainbowMage.OverlayPlugin.PluginMain.LoadConfig()
8/24/2015 4:51:41 PM: Info: LoadConfig: Creating new configuration.
8/24/2015 4:51:41 PM: Info: InitPlugin: Initialized.

I've reinstalled act many times, and downloaded the full package of the overlay plugin many times, and still that pops up every time I try to enable it. Help anyone?

**Comment by viseriod** [comment]
how'd you fix it?

**Comment by Lockaroonie** [comment]
ah sorry, its silly to end a thread without writing the solution. I believe the way I fixed this and similar issues is i uninstalled the program entirely, including all saved settings, restarted my computer, then reinstalled the program. simply restarting the computer without reinstalling the program might work too, give that a try first so you don't have to lose all saved settings and stuff.
